### ISSUE TITLE
Adding collenchyma

### ISSUE THREAD

**Issue by gbersac** [kud1ing/awesome-rust#101]
Why not adding [collenchyma](https://github.com/autumnai/collenchyma) ? GPU programming is important !

**Comment by kud1ing** [comment]
Yes, why not create a pull request? :)

**Comment by gbersac** [comment]
Because I am lazy :)

Envoyé de mon smartphone BlackBerry 10 sur le réseau Orange.
De: kud1ing
Envoyé: jeudi 10 décembre 2015 15:56
À: kud1ing/awesome-rust
Répondre à: kud1ing/awesome-rust
Cc: Guillaume Bersac
Objet: Re: [awesome-rust] Adding collenchyma (#101)


Yes, why not create a pull request? :)

---
