### ISSUE TITLE
conrod GUI category is a little misleading

### ISSUE THREAD

**Issue by mitchmindtree** [kud1ing/awesome-rust#110]
Hey there :)

I just notices that conrod is listed under an SDL2 subheading in the GUI section. Conrod actually supports multiple backends, including SDL2, GLFW and glutin, and also allows for implementing custom backends via backend traits.

I haven't yet submitted a PR as I'm unsure how you'd wish to handle this fix. Perhaps a new "Any Platform" or "Platform Agnostic" subheading could be made? Let me know your thoughts and i'd be happy to do a PR (unless you're happy to make the fix yourself).

**Comment by kud1ing** [comment]
Hey, thank you. I agree. For the time being, i've moved Conrod one level up. Will think about and maybe do something else in the future.
