### ISSUE TITLE
GSL

### ISSUE THREAD

**Issue by GuillaumeGomez** [kud1ing/awesome-rust#18]
Hi,

I'm currenly writing (for a few months now) a binding for the [GSL library](http://www.gnu.org/software/gsl/) [here](https://github.com/GuillaumeGomez/rust-GSL). Would it be possible to add it please ?

**Comment by kud1ing** [comment]
Sure, can you send a pull request?

**Comment by GuillaumeGomez** [comment]
Here it is #20. Thanks !

**Comment by kud1ing** [comment]
Thanks, merged.
