### ISSUE TITLE
Incorrect game engine entry

### ISSUE THREAD

**Issue by ebkalderon** [kud1ing/awesome-rust#197]
As of early 2016, Amethyst is no longer a lone-developer project. :smile: As such, the new GitHub repository is located at http://github.com/amethyst/amethyst, the website is https://www.amethyst.rs/, and the correct Travis CI shield is at https://travis-ci.org/amethyst/amethyst.svg?branch=master.

Also, in regards to `rust.libhunt.com`, which I assume this repository is affiliated with, I don't think there should be a `Game Development/Amethyst` sub-category. The only entries in there are `amethyst` and an unrelated crate called `challonge-rs`.

I'm willing to make a PR to fix these issues. That said, this is an excellent list! Keep up the great work.

**Comment by kud1ing** [comment]
Thank you for the kind words and taking the time to improve this list. But first and foremost thanks for writing interesting Rust code. Without it this list would be empty. :)

**Comment by kud1ing** [comment]
This list is not affiliated with rust.libhunt.com. They are importing the data from this list, but afaik keep the data that is submitted there for themselves.
