### ISSUE TITLE
rust-learning

### ISSUE THREAD

**Issue by ctjhoa** [kud1ing/awesome-rust#32]
Hi,
I have a project [rust-learning](https://github.com/ctjhoa/rust-learning) which tend to aggregate all the useful resources to learn rust. I'll add a link to awesome-rust in my README.

IMO learning resources and tools/libraries should have a separate repos because of maintenance issues and too much content to manage.
I would like to know your point of view about that, I saw that you have a "resources" section too.

**Comment by kud1ing** [comment]
I agree, no need to duplciate that.

**Comment by ctjhoa** [comment]
See #42
