### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by arthurvr** [kud1ing/awesome-rust#51]
> thoughtram/clog — a conventional changelog port (generates a changelog from git metadata) 

The link on "a conventional changelog port" seems broken.

**Comment by kud1ing** [comment]
Thanks, i've linked this blog post instead: http://blog.thoughtram.io/announcements/tools/2014/09/18/announcing-clog-a-conventional-changelog-generator-for-the-rest-of-us.html
Could not find a stable, official link. Feel free to submit a PR with something more appropraite.
