### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by arthurvr** [kud1ing/awesome-rust#52]
This repo misses a license. You could use https://github.com/sindresorhus/awesome#license as inspiration.

**Comment by kud1ing** [comment]
Thank you. Applied it.
Legally it's probably more complicated than that, though.

**Comment by palfrey** [comment]
It took me a little bit to figure this out. If you added https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt as LICENCE.txt to the repository, Github should pick it up and apply it to the repo.
